version: 1.0.{build}

os:
  - Windows Server 2016   # Используем доступный образ

environment:
  matrix:
    - PYTHON: "3.9"

before_build:
  - echo "Setting up the environment"
  - python -m venv venv
  - venv\Scripts\activate
  - pip install -r requirements.txt

build_script:
  - python -m unittest discover  # Запуск тестов (если они есть)

after_build:
  - echo "Build complete, preparing for deployment"

deploy:
  provider: GitHub
  username: $GH_USERNAME
  password: $GH_TOKEN
  repository: "nikitagreb1/lab1"
  on:
    branch: main
