version: 1.0.{build}

os:
  - Visual Studio 2019  # Используем Visual Studio 2019

environment:
  matrix:
    - PYTHON: "3.9"

before_build:
  - echo "Setting up the environment"
  - python -m venv venv
  - venv\Scripts\activate
  - pip install -r requirements.txt
  - echo "GH_TOKEN: $GH_TOKEN"  # Проверим значение переменной



build_script:
  - echo "Running custom build script"
  #- python -m unittest discover  # Запуск тестов (если они есть)

after_build:
  - echo "Build complete, preparing for deployment"

deploy:
  provider: GitHub
  username: $GH_USERNAME
  password: $GH_TOKEN
  repository: "nikitagreb1/lab1"
  on:
    branch: main

